name: Debug Database State

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Database
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Wrangler
        run: npm install -g wrangler
      
      - name: Debug database state
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "🔍 Debugging database state..."
          
          # Run debug queries
          wrangler d1 execute navicore-music --file=debug-database.sql || echo "Debug queries failed"
          
          echo ""
          echo "📊 Checking database binding..."
          echo "Database name from wrangler.toml: navicore-music"
          echo "Database ID from wrangler.toml: c09c462b-e2f1-420d-a3fa-d0e8bc19736e"
          
          echo ""
          echo "🔍 Attempting direct table count..."
          wrangler d1 execute navicore-music --command="SELECT 'TRACKS_TABLE_EXISTS' as check, COUNT(*) as count FROM tracks;" || echo "Tracks table doesn't exist or query failed"
          
          echo ""
          echo "🔍 Checking if we can create a test table..."
          wrangler d1 execute navicore-music --command="CREATE TABLE IF NOT EXISTS test_table (id INTEGER PRIMARY KEY, test TEXT);" || echo "Cannot create test table"
          wrangler d1 execute navicore-music --command="INSERT INTO test_table (id, test) VALUES (1, 'GitHub Action Test');" || echo "Cannot insert into test table"
          wrangler d1 execute navicore-music --command="SELECT * FROM test_table;" || echo "Cannot read from test table"
          wrangler d1 execute navicore-music --command="DROP TABLE IF EXISTS test_table;" || echo "Cannot drop test table"
          
          echo ""
          echo "✅ Debug complete"